Import Debian packaging for 2.59.3
This is an unmodified copy of the current state of
salsa/debian/experimental.

Signed-off-by: Philip Withnall <withnall@endlessm.com>

https://phabricator.endlessm.com/T25384#682620

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -1,8 +1,5 @@
 #!/usr/bin/make -f
 
-include /usr/share/gnome-pkg-tools/1/rules/gnome-get-source.mk
-
-GNOME_MODULE := glib
 binaries := $(shell dh_listpackages)
 
 export DEB_BUILD_MAINT_OPTIONS=hardening=+bindnow
@@ -21,9 +18,37 @@ DEB_LDFLAGS_MAINT_APPEND += -Wl,-O1
 include /usr/share/dpkg/default.mk
 
 %:
-	dh $@ --with gnome,python3
+	dh $@ --with gnome,python3 --buildsystem=meson
 
+override_dh_autoreconf:
+	@:
+
+ifneq ($(filter hppa,$(DEB_HOST_ARCH_CPU)),)
+stack_grows_up = true
+else
+stack_grows_up = false
+endif
+
+ifneq ($(filter kfreebsd,$(DEB_HOST_ARCH_OS)),)
+have_non_stub_xattr = false
+else
+have_non_stub_xattr = true
+endif
+
+export DH_MESON_CROSS_FILE = debian/cross.txt
+
+# We use our own copy of debcrossgen to work around unimplemented feature
+# request https://bugs.debian.org/912559
 override_dh_auto_configure:
+ifneq ($(DEB_HOST_ARCH),$(DEB_BUILD_ARCH))
+	debian/debcrossgen \
+		--set have_c99_snprintf=true \
+		--set have_c99_vsnprintf=true \
+		--set have_strlcpy=false \
+		--set have_unix98_printf=true \
+		--set growing_stack=$(stack_grows_up) \
+		-o debian/cross.txt
+endif
 	dh_auto_configure \
 		--builddirectory=debian/build/deb \
 		-- \
@@ -43,7 +68,8 @@ override_dh_clean:
 	rm -rf $(CURDIR)/debian/build \
 	       $(CURDIR)/debian/install \
 	       $(CURDIR)/debian/tmp-xdg-runtime-dir
-	dh_clean -Xorg.gtk.test.gschema.xml.orig
+	dh_clean -Xorg.gtk.test.gschema.xml.orig -Xorg.gtk.test.gschema.override.orig
+
 
 override_dh_makeshlibs:
 	dh_makeshlibs -plibglib2.0-tests -n
@@ -77,12 +103,52 @@ unexport XDG_DATA_DIRS
 export DBUS_SESSION_BUS_ADDRESS=this-should-not-be-used-and-will-fail:
 
 ifeq ($(DEB_HOST_ARCH_OS), linux)
-override_dh_auto_test-arch:
-	# Remove LD_PRELOAD so we don't run with fakeroot, which makes dbus-related tests fail
-	env -u LD_PRELOAD dh_auto_test --builddirectory=debian/build/deb -- -k check -j1
+handle_test_failure := exit $$?
 else
+handle_test_failure := true
+endif
+
+# Upstream test timeouts assume an otherwise unloaded system, but that
+# isn't necessarily the case for a porterbox or multiple parallel builds
+test_timeout_multiplier = 3
+
+ifneq ($(filter arm hppa mips% sparc%,$(DEB_HOST_ARCH_CPU)),)
+$(info Slow architecture detected, increasing test timeout)
+test_timeout_multiplier = 5
+endif
+
+ifneq ($(filter m68k riscv64 sh4,$(DEB_HOST_ARCH_CPU)),)
+$(info Architecture with qemu buildds detected, increasing test timeout a lot)
+test_timeout_multiplier = 20
+endif
+
 override_dh_auto_test-arch:
-	env -u LD_PRELOAD dh_auto_test --builddirectory=debian/build/deb -- -k check -j1 || true
+ifeq (,$(filter nocheck,$(DEB_BUILD_OPTIONS)))
+	# Remove LD_PRELOAD so we don't run with fakeroot, which makes dbus-related tests fail
+	# First run the non-flaky tests, and fail the build if they fail (on linux)
+	env -u LD_PRELOAD \
+		DEB_BUILD_TIME_TESTS=1 \
+		LC_ALL=C.UTF-8 \
+		MESON_TESTTHREADS=1 \
+	meson test -C debian/build/deb \
+		--no-rebuild \
+		--num-processes 1 \
+		--timeout-multiplier $(test_timeout_multiplier) \
+		--no-suite flaky \
+		--verbose \
+	|| $(handle_test_failure)
+	# and then run the flaky ones, but ignore them failing
+	env -u LD_PRELOAD \
+		DEB_BUILD_TIME_TESTS=1 \
+		LC_ALL=C.UTF-8 \
+		MESON_TESTTHREADS=1 \
+	meson test -C debian/build/deb \
+		--no-rebuild \
+		--num-processes 1 \
+		--timeout-multiplier $(test_timeout_multiplier) \
+		--suite flaky \
+		--verbose \
+	|| true
 endif
 
 # Skip build-time tests if all we are building is documentation; running
@@ -96,39 +162,51 @@ export XDG_RUNTIME_DIR=$(CURDIR)/debian/tmp-xdg-runtime-dir
 # a build fails
 export VERBOSE=1
 
+ifeq ($(DEB_HOST_ARCH_OS),linux)
+is_linux := true
+enable_selinux := enabled
+else
+is_linux := false
+enable_selinux := disabled
+endif
+
+ifneq ($(filter hurd kfreebsd,$(DEB_HOST_ARCH_OS)),)
+use_fam := true
+else
+use_fam := false
+endif
+
 # configure flags
 DEB_CONFIGURE_EXTRA_FLAGS := \
-			--with-html-dir=\$${prefix}/share/doc/libglib2.0-doc \
-			--libexecdir=\$${prefix}/lib/glib2.0 \
-			--with-python=/usr/bin/python3 \
-			--with-pcre=system
+	--libexecdir=lib/glib2.0 \
+	-Dinternal_pcre=false \
+	$(NULL)
 
 DEB_CONFIGURE_FLAGS_deb := \
-			--enable-static \
-			--enable-installed-tests \
-			--enable-always-build-tests \
-			--enable-debug=minimum
+	--default-library both \
+	-Dfam=$(use_fam) \
+	-Dinstalled_tests=true \
+	-Dlibmount=$(is_linux) \
+	-Dman=true \
+	-Dselinux=$(enable_selinux) \
+	-Dsystemtap=true \
+	-Dxattr=$(have_non_stub_xattr) \
+	$(NULL)
 
 ifneq ($(filter libglib2.0-doc,$(binaries)),)
-DEB_CONFIGURE_FLAGS_deb += --enable-gtk-doc
+DEB_CONFIGURE_FLAGS_deb += -Dgtk_doc=true
 else
-DEB_CONFIGURE_FLAGS_deb += --disable-gtk-doc
+DEB_CONFIGURE_FLAGS_deb += -Dgtk_doc=false
 endif
-
-# libmount is available on linux only
-ifeq ($(DEB_HOST_ARCH_OS), linux)
-  DEB_CONFIGURE_FLAGS_deb += \
-			--enable-libmount
-else
-  DEB_CONFIGURE_FLAGS_deb += \
-			--disable-libmount
-endif
-
 
 DEB_CONFIGURE_FLAGS_udeb := \
-			--disable-selinux \
-			--disable-libmount \
-			--disable-gtk-doc
+	--default-library shared \
+	-Dgtk_doc=false \
+	-Dinstalled_tests=false \
+	-Dlibmount=false \
+	-Dselinux=disabled \
+	-Dxattr=$(have_non_stub_xattr) \
+	$(NULL)
 
 override_dh_auto_build:
 	mkdir -p debian/tmp-xdg-runtime-dir
@@ -144,28 +222,27 @@ override_dh_auto_install:
 		    debian/libglib2.0-0.$$script.in \
 		    > debian/libglib2.0-0.$$script ; \
 	done
-	dh_auto_install -plibglib2.0-tests --sourcedir=debian/build/deb
 ifneq ($(filter %-udeb,$(binaries)),)
 	dh_auto_install -plibglib2.0-udeb --builddirectory=debian/build/udeb --destdir=debian/install/udeb
 endif
 	dh_auto_install --remaining-packages --builddirectory=debian/build/deb --destdir=debian/install/deb
 
 override_dh_python3:
+	# dh_python3 can't process both a private directory and /usr/bin
+	# in the same invocation
 	dh_python3 -plibglib2.0-dev-bin /usr/share/glib-2.0/codegen
+	dh_python3 -plibglib2.0-dev-bin
 
 override_dh_install:
 	# Unwanted bits from the .deb build
-	rm -f debian/install/deb/lib/*/*.la
-	rm -f debian/install/deb/usr/lib/*/*.la
-	rm -f debian/install/deb/usr/lib/glib2.0/installed-tests/glib/*.la
-	rm -f debian/install/deb/usr/lib/glib2.0/installed-tests/glib/modules/*.la
 	rm -fr debian/install/deb/usr/share/glib-2.0/codegen/__pycache__
-	# Re-created by .links to point into /lib
-	rm -f debian/install/deb/usr/lib/*/libglib-2.0.so
+	# https://gitlab.gnome.org/GNOME/glib/issues/1539
+	chmod -v 0644 debian/install/deb/usr/lib/glib2.0/installed-tests/glib/desktop-files/usr/applications/org.gnome.clocks.desktop
+	chmod -v 0644 debian/install/deb/usr/lib/glib2.0/installed-tests/glib/echo-script.bat
+	chmod -v 0644 debian/install/deb/usr/share/bash-completion/completions/gio
+	chmod -v 0644 debian/install/deb/usr/share/glib-2.0/codegen/codegen_main.py
 ifneq ($(filter %-udeb,$(binaries)),)
 	# Unwanted bits from the .udeb build
-	rm -f debian/install/udeb/lib/*/*.la
-	rm -f debian/install/udeb/usr/lib/*/*.la
 	rm -f debian/install/udeb/usr/lib/*/*.so
 	rm -fr debian/install/udeb/usr/share/gdb
 	rm -fr debian/install/udeb/usr/share/gettext/its
@@ -175,12 +252,10 @@ ifneq ($(filter %-udeb,$(binaries)),)
 	rm -fr debian/install/udeb/usr/share/man
 	dh_install -plibglib2.0-udeb --sourcedir=debian/install/udeb
 endif
-	# Put the gdb script in .../gdb/auto-load/lib, as we install libglib*.so in there
-	mkdir -p debian/install/deb/usr/share/gdb/auto-load/lib/${DEB_HOST_MULTIARCH}/
-	mv debian/install/deb/usr/share/gdb/auto-load/usr/lib/${DEB_HOST_MULTIARCH}/libglib*so*py \
-		debian/install/deb/usr/share/gdb/auto-load/lib/${DEB_HOST_MULTIARCH}/
 	dh_install --remaining-packages --sourcedir=debian/install/deb
 
 override_dh_missing:
-	dh_missing --sourcedir=debian/install/udeb --fail-missing
 	dh_missing --sourcedir=debian/install/deb --fail-missing
+ifneq ($(filter %-udeb,$(binaries)),)
+	dh_missing --sourcedir=debian/install/udeb --fail-missing
+endif
diff --git a/debian/tests/build b/debian/tests/build
--- a/debian/tests/build
+++ b/debian/tests/build
@@ -2,26 +2,126 @@
 # autopkgtest check: Build and run a program against glib, to verify that the
 # headers and pkg-config file are installed correctly
 # (C) 2012 Canonical Ltd.
-# Author: Martin Pitt <martin.pitt@ubuntu.com>
+# (C) 2018 Simon McVittie
+# Authors: Martin Pitt <martin.pitt@ubuntu.com>, Simon McVittie
 
-set -e
+set -eux
+
+mode=dynamic
+
+getopt_temp="$(getopt -o '' --long 'static' -n debian/tests/build -- "$@")"
+eval set -- "$getopt_temp"
+
+while true; do
+    case "$1" in
+        (--static)
+            mode=static
+            shift
+            continue
+            ;;
+
+        (--)
+            shift
+            break
+            ;;
+
+        (*)
+            echo "getopt: Internal error" >&2
+            exit 2
+    esac
+done
 
 WORKDIR=$(mktemp -d)
 trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM
 cd $WORKDIR
-cat <<EOF > glibtest.c
+cat <<EOF > glib.c
 #include <glib.h>
 
-int main()
+int main(void)
 {
     g_assert_cmpint (g_strcmp0 (NULL, "hello"), ==, -1);
-    g_assert_cmpstr (g_find_program_in_path ("bash"), ==, "/bin/bash");
+    g_assert_cmpstr (g_getenv ("foo"), ==, "bar");
+    return 0;
+}
+EOF
+cat <<EOF > gobject.c
+#include <glib-object.h>
+
+int main(void)
+{
+    g_assert_cmpuint (G_TYPE_OBJECT, !=, G_TYPE_INVALID);
+    return 0;
+}
+EOF
+cat <<EOF > gio.c
+#include <gio/gio.h>
+
+int main(void)
+{
+    g_assert_cmpuint (G_TYPE_FILE, !=, G_TYPE_INVALID);
+    return 0;
+}
+EOF
+cat <<EOF > gio-unix.c
+#include <gio/gunixfdlist.h>
+
+int main(void)
+{
+    g_assert_cmpuint (G_TYPE_UNIX_FD_LIST, !=, G_TYPE_INVALID);
+    return 0;
+}
+EOF
+cat <<EOF > gmodule.c
+#include <gmodule.h>
+
+int main(void)
+{
+    GModule *module;
+
+    g_assert_true (g_module_supported ());
+    module = g_module_open (NULL, 0);
+    g_assert_nonnull (module);
+    g_assert_true (g_module_close (module));
+    return 0;
+}
+EOF
+cat <<EOF > gthread.c
+#include <glib.h>
+
+static gpointer
+other_cb (gpointer nil)
+{
+  return "hello";
+}
+
+int main(void)
+{
+    GThread *other;
+    gpointer ret;
+
+    other = g_thread_new ("other", other_cb, NULL);
+    g_assert_nonnull (other);
+    ret = g_thread_join (other);
+    g_assert_cmpstr (ret, ==, "hello");
     return 0;
 }
 EOF
 
-gcc -o glibtest glibtest.c `pkg-config --cflags --libs glib-2.0`
-echo "build: OK"
-[ -x glibtest ]
-./glibtest
-echo "run: OK"
+for lib in glib gobject gio gio-unix gmodule gthread; do
+    cflags=
+    pcflags=
+    packages="${lib}-2.0"
+
+    case "$mode" in
+        (static)
+            cflags=-static
+            pcflags=--static
+            ;;
+    esac
+
+    gcc $cflags -o ${lib}-$mode ${lib}.c `pkg-config $pcflags --cflags --libs ${packages}`
+    echo "build ($lib, $mode): OK"
+    [ -x ${lib}-$mode ]
+    foo=bar ./${lib}-$mode
+    echo "run ($lib, $mode): OK"
+done
